apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c1
  janus-idp.io/tekton: c1
  backstage.io/kubernetes-id: c1
  backstage.io/kubernetes-namespace: test-all 
  app.kubernetes.io/part-of: c1
resources:
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml

